name: myapp
description: A new Flutter project.

publish_to: 'none' 


environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bottom_drawer: ^0.0.5
  json_annotation: ^4.8.1 
  http: ^1.1.0
  # http: ^0.13.3
  google_maps_flutter: ^2.5.0
  # permission: ^0.1.7
  # permission_handler: ^10.4.3
  # permission: ^0.0.3
  permission_handler: ^10.4.3
  cupertino_icons: ^1.0.2
  geolocator: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_model: ^1.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assist/icon_fraind.png

  uses-material-design: true

